# TCL File Generated by Component Editor 15.1
# Wed Nov 30 14:18:13 MSK 2016
# DO NOT MODIFY


# 
# gain "gain" v1.0
#  2016.11.30.14:18:13
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module gain
# 
set_module_property DESCRIPTION ""
set_module_property NAME gain
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gain
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gainHw
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gainHw.sv SYSTEM_VERILOG PATH ../rtl/gainHw.sv TOP_LEVEL_FILE
add_fileset_file gain.sv SYSTEM_VERILOG PATH ../rtl/gain.sv
add_fileset_file gainAvs.sv SYSTEM_VERILOG PATH ../rtl/gainAvs.sv
add_fileset_file gainMult.sv SYSTEM_VERILOG PATH ../rtl/gainMult.sv


# 
# parameters
# 
add_parameter A_WDT INTEGER 16 "width for a"
set_parameter_property A_WDT DEFAULT_VALUE 16
set_parameter_property A_WDT DISPLAY_NAME A_WDT
set_parameter_property A_WDT WIDTH ""
set_parameter_property A_WDT TYPE INTEGER
set_parameter_property A_WDT UNITS None
set_parameter_property A_WDT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property A_WDT DESCRIPTION "width for a"
set_parameter_property A_WDT HDL_PARAMETER true
add_parameter COEF_WDT INTEGER 16 "width for coef, max = 32, must be even "
set_parameter_property COEF_WDT DEFAULT_VALUE 16
set_parameter_property COEF_WDT DISPLAY_NAME COEF_WDT
set_parameter_property COEF_WDT WIDTH ""
set_parameter_property COEF_WDT TYPE INTEGER
set_parameter_property COEF_WDT UNITS None
set_parameter_property COEF_WDT ALLOWED_RANGES 2:32
set_parameter_property COEF_WDT DESCRIPTION "width for coef, max = 32, must be even "
set_parameter_property COEF_WDT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 1
set_interface_property avs readWaitStates 0
set_interface_property avs readWaitTime 0
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 32
add_interface_port avs avs_readdata readdata Output 32
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point asi
# 
add_interface asi avalon_streaming end
set_interface_property asi associatedClock clk
set_interface_property asi associatedReset reset
set_interface_property asi dataBitsPerSymbol 8
set_interface_property asi errorDescriptor ""
set_interface_property asi firstSymbolInHighOrderBits true
set_interface_property asi maxChannel 0
set_interface_property asi readyLatency 0
set_interface_property asi ENABLED true
set_interface_property asi EXPORT_OF ""
set_interface_property asi PORT_NAME_MAP ""
set_interface_property asi CMSIS_SVD_VARIABLES ""
set_interface_property asi SVD_ADDRESS_GROUP ""

add_interface_port asi asi_valid valid Input 1
add_interface_port asi asi_data data Input A_WDT


# 
# connection point aso
# 
add_interface aso avalon_streaming start
set_interface_property aso associatedClock clk
set_interface_property aso associatedReset reset
set_interface_property aso dataBitsPerSymbol 8
set_interface_property aso errorDescriptor ""
set_interface_property aso firstSymbolInHighOrderBits true
set_interface_property aso maxChannel 0
set_interface_property aso readyLatency 0
set_interface_property aso ENABLED true
set_interface_property aso EXPORT_OF ""
set_interface_property aso PORT_NAME_MAP ""
set_interface_property aso CMSIS_SVD_VARIABLES ""
set_interface_property aso SVD_ADDRESS_GROUP ""

add_interface_port aso aso_valid valid Output 1
add_interface_port aso aso_data data Output A_WDT

